language: cpp
sudo: required
dist: xenial

# env:
#   - ARCH=x86_64 DOCKER_IMAGE=amd64/ubuntu:trusty
#   - ARCH=i686 DOCKER_IMAGE=i386/ubuntu:trusty

matrix:
  fast_finish: true
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env: COMPILER=g++-5 CXX=g++-5
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.8
        packages:
        - clang-3.8
    env: COMPILER=clang++-3.8

before_install:
- sudo apt-get update -qq
- sudo apt-get --force-yes install build-essential git-core cmake libsqlite3-dev qt5-default qttools5-dev-tools libsqlcipher-dev qtbase5-dev libqt5scintilla2-dev libqcustomplot-dev qttools5-dev


install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script:
- mkdir build
- mkdir build_cipher
- mkdir appbuild
- mkdir appdir
- cd build
- cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DENABLE_TESTING=ON ..
- make
- ctest -V
- cd ../build_cipher
- cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DENABLE_TESTING=ON -Dsqlcipher=1 ..
- make
- ctest -V
- cd ../appbuild
- cmake -DCMAKE_INSTALL_PREFIX:PATH=../appdir/usr -Wno-dev -Dsqlcipher=1 -DSQLITE_ENABLE_JSON1=1 ..
- make install
- cd ..
- git rev-list HEAD --count
- wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage"
- chmod a+x linuxdeployqt-6-x86_64.AppImage
- export VERSION=$(printf "`master`-`git rev-list HEAD --count`-` git -C . rev-parse --short HEAD`")    #$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
- ./linuxdeployqt-6-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

deploy:
  provider: releases
  api_key:
    secure: "GKTwUkTHQCr+LJ2cfRPFHJZnyoKSLRoDXhtc/vyCo4Qj0V9Mq89W+ytRyiyd6UlduuZBvqPOXEQDrlrgLmoXQ8o91UoaXurF8PS74m/lniTLCJiH9Wqg5LvJBwRYMLi8DAqZHN6hu7xESAjgsapOMg3KoSVdzvgXu4Pp/Kxa8R0="
  file_glob: true
  file: /*
  skip_cleanup: true
  draft: true
