version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: x64
clone_folder: C:\git_repos\sqlitebrowser
environment:
  QTDIR: C:\Qt\5.15.1\msvc2019_64
  PATH: '%PATH%;%QTDIR%\bin'
install:
- cmd: >-
    dir C:\Qt\5.13.2\msvc2017_64
    
    MKDIR C:\dev

    MKLINK /D C:\dev\OpenSSL-Win64 C:\OpenSSL-Win64
    
    MKLINK /D C:\dev\OpenSSL-Win32 C:\OpenSSL-Win32
    
    REM MKLINK /D C:\git_repos\sqlitebrowser\builds C:\builds

    appveyor DownloadFile "https://www.sqlite.org/2020/sqlite-amalgamation-3340000.zip" -FileName C:\dev\sqlite_amal.zip

    7z x C:\dev\sqlite_amal.zip

    move sqlite-amalgamation-3340000 C:\dev\SQLite-Win64

    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

    cd C:\dev\SQLite-Win64

    cl sqlite3.c -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_STAT4 -DSQLITE_SOUNDEX -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_RTREE -DSQLITE_MAX_ATTACHED=125 -DSQLITE_API=__declspec(dllexport) -link -dll -out:sqlite3.dll

    cd C:\git_repos\sqlitebrowser

    exit


    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

    cmake -G "Visual Studio 16 2019" -Wno-dev

    dir
after_build:
- cmd: dir

    MKLINK /D C:\git_repos\sqlitebrowser\builds "C:\Program Files (x86)\sqlitebrowser"
cache:
- '**.obj'
- libs
- sqlitebrowser_autogen
- sqlitebrowser.dir
build:
  project: INSTALL.vcxproj
  verbosity: minimal
artifacts:
- path: Debug
- path: Release
- path: builds